### ISSUE TITLE
Unable to build ColumnFormatter for production

### ISSUE THREAD

**Issue by tchagan** [SharePoint/sp-dev-solutions#26]
#### Category
- [ ] Question
- [X] Bug
- [ ] Enhancement

#### Expected or Desired Behavior
I wish to package the solution for production, by running gulp build, gulp bundle --ship, gulp package-solution --ship

#### Observed Behavior
I run gulp build, then gulp --ship, at this point the process does not move beyond 
Starting subtask 'webpack' ...

#### Steps to Reproduce
Running npm 6.1.0, node 8.11.1
Download solution 
run npm install
run gulp build
run gulp bundle --ship

**Comment by itsknob** [comment]
It looks like this might be related to #7, where Chris Kent mentioned that the process takes over 30 minutes to complete. He said that's why the package solution was included.

**Comment by ypcode** [comment]
Hi,

as Stephen mentions, it’s due to the Monaco Editor used in the solution. Somehow it is not optimized for the SPFx bundling. I definitely will try to improve that when I get a chance.

But it does work very slowly even if it looks hanging forever.

But again, if you want to use the solution as is, the sppkg is shipped with even a PowerShell install script (in the package folder).

Thanks for the interest in the solution

And thank you Stephen for your help :)

**Comment by VesaJuvonen** [comment]
Closing as seem to be indeed related on the #7 and no active discussion since that comment.
