### ISSUE TITLE
Resize default file name column

### ISSUE THREAD

**Issue by Virgile59** [SharePoint/sp-dev-solutions#35]
#### Category
- [*] Question

Hello, first of all thank you for your work.
Despite my documentation I can not resize (in width) the file name column (clickable). I use SharePoint Office 365 modern interface.

Thanks for your help.

**Comment by thechriskent** [comment]
Thanks for your question! However, this issues list is for the solutions included in this repository and isn't intended for general issues.

If you are attempting to do the above via an API you can submit this as an issue on https://aka.ms/spdev-issues

Otherwise, the Microsoft tech community, Stack Exchange, etc. provide additional options for support.
