### ISSUE TITLE
[ModernSearch] [WIP] Allow refiners to be displayed in their own web part

### ISSUE THREAD

**Issue by YannickRe** [SharePoint/sp-dev-solutions#64]
- [X] Enhancement

#### Feature enhancement
Just a FYI to let you know I'm working on a feature to (if wanted) show to Refiners in their own web part instead of in the main web part as a sliding panel. I took great care in making sure that both methods would still work.

I know that it's not really the modern look and feel, but a lot of customers are still asking for a similar experience as with the Enterprise Search Center.

#### Development status
- [X] Run as a separate web part, data connections flowing in both ways
- [x] Display spinner/loading animation on Refiners web part when reiner selected
- [ ] Test with PnP provisioning making sure it's possible to provision a Search Center
- [ ] Add readme

#### Branch
If you want to follow along => https://github.com/YannickRe/sp-dev-solutions/tree/feature/searchRefiners

**Comment by FranckyC** [comment]
Nice one @YannickRe ! Is it ready to test yet using your feature branch?

**Comment by YannickRe** [comment]
Yes, it’s finished. Just missing the readme and a thorough test with the Provisioning engine.

**Comment by FranckyC** [comment]
Ideally I would remove the old refiner method embedded in the search results and thus introduce a breaking change. Both methods mean duplicate code somewhere, which is not a good approach. The new WP could still have multiple UI options (like panel or visible filters). We also could think to introduce templating for refiners as well maybe. What do you think @wobba ?

**Comment by FranckyC** [comment]
@YannickRe I'll take a look

**Comment by YannickRe** [comment]
I tried to reduce the code duplication, splitting code to a global Filter component out if the FilterPanel component. Both the FilterPanel and the webpart now use this Filter component.

I like the idea of the templating for the Refiners, thought about it, but decided to start with this “simple” version first.

**Comment by wobba** [comment]
I think introducing this and keeping the built-in is a great start. Question is if refiner props should be specified in the result wp, if you are using a separate wp, or passed in somehow. I'd like to avoid a breaking change if possible. @YannickRe how do you specify refiner settings?

**Comment by YannickRe** [comment]
I kept configuration in the original webpart. I have no breaking changes, the original webpart exposes the necessary values to the refiner webpart. The refiner webpart passes the selected values back to the original webpart.

You decide in the property pane if you want to use the built in refiners or the refiner webpart.

**Comment by wobba** [comment]
@YannickRe makes sense, tag me when you do a PR and I'll review and test the code.

**Comment by FranckyC** [comment]
@YannickRe Just tested it. I'm ok with the concept but I have few comments:
- Not sure about the loading icon here because the component does not fetch anything actually. I would remove it.
- Also when connecting to the search refiners to the search results, you could use a single dynamic data object property instead of 3 different properties.
- Please use the React container pattern (i.e. the same naming convention as other WPs to be consistent. It will be easier to add other default layouts in the future just by adding a sub folder.
- Clean the SASS style sheet please.
- It is weird to have a search refiners WP and actually configure the refiners in the...search results WP. I think we could move this configuration to the refiner WP itself. It leads to my previous concern: remove completely the refiners from the search results WP and do all refiners related configuration in a dedicated component. In my opinion, it does not matter if it introduces a breaking change since we can mitigate this point with a migration procedure. Also people are not forced to migrate. If they want, the update should be fairly easy (copy/paste of the settings).

In general, before releasing it, I think we have to provide at least the following options:
- different predefined layouts (horizontal with dropdowns and vertical with groups)
- Conditions behavior between filters and/or filter values (AND or OR). It's a very common request I get from customers.

**Comment by wobba** [comment]
I'll agree to the breaking change as I'm not using refiner myself in prod ;-) @taraldga is though but not a lot. @YannickRe how hard would it be to implement the changes proposed by @FranckyC?

**Comment by FranckyC** [comment]
@YannickRe I could help on this one. I could take your feature branch as a start. Sorry for all the comments and thoughts but it is critical component in the search experience. You didn't choose an easy one ;)

**Comment by YannickRe** [comment]
@FranckyC I'm known to aim high ;) And I agree it's a critical component, my current project has this as a top priority.

About the comments:
1. Agreed to remove the loading icon. Implementation gets a lot simpler and can use it's own state management if we can do breaking changes and remove the current filter experience. This would eliminate the need for the loading icon. I did this now, because of the current implementation it takes a while to be "responsive" and show that you selected a filter.
2. Probably true, but I'll need some help here. Very new to this Dynamic Property thing, I was just glad to have this working.
3. Basically renaming SearchRefiners.tsx to SearchRefinersContainer.tsx? Do you want the subfolder already? (SearchBoxWebPart doesn't have the subfolder, SearchNavigationWebPart doesn't do the naming convention ;) )
4. Sorry, missed this.
5. Agreed, this means moving the property pane stuff from Search Results to Search Refiners. I'll rename the web part from "Search Results with Refiners" to just "Search Results".

I'll take care of 1, 3, 4 and 5 tomorrow. I'll see how that affects 2, and get back to you.
If I misinterpreted your comments, please let me know as well.

About the layout options:
- I don't think they need to be in there from the start, can't they be added as a future improvement? I'll fix the basics, and do the pull request so if these options are necessary, I'll leave these options to you.

@wobba As said, leaving the layout options aside for the moment, these changes shouldn't be too hard to implement. Couple hours tops.

**Comment by FranckyC** [comment]
@YannickRe Ok you can submit your PR when ready ;) I will probably enhance the base implementation with mentioned points above. To summarize, you do the 'split' part and I complete with the details requiring deeper component knowledge. Sounds good?

**Comment by YannickRe** [comment]
Great. Should have started with separating out the pagination ;)

**Comment by YannickRe** [comment]
@wobba @FranckyC Pull request submitted!

**Comment by YannickRe** [comment]
Merged, so this can be closed now.
