### ISSUE TITLE
[ModernSearch] Search Refiner Web Part doesn't reset on new query

### ISSUE THREAD

**Issue by YannickRe** [SharePoint/sp-dev-solutions#71]
#### Category
- [X] Bug

#### Expected or Desired Behavior
I do a search query (v3.0.0.0), then apply a refiner with the Search Refiners Web Part and then do a new search query, I expect the refiners to be reset.

#### Observed Behavior
The refiners stay applied on the new search query.

#### Steps to Reproduce
![RefinerWebPartProblem](https://user-images.githubusercontent.com/9973962/54085703-12de3b00-4341-11e9-93c0-d7b8ba14b848.gif)

@FranckyC : I believe this was introduced with the refactoring (it was working in my pull request), any idea how to fix?

**Comment by FranckyC** [comment]
@YannickRe This bug was here before and it applies on all 'range' filters. This is because new refiners are generated after a query and we lost trace of the previous value (we do the comparison on the RefinementToken value to see if the filter is checked).

I think instead of displaying the raw range value determined by SharePoint, we should set predefined ones to avoid this type of issue (last 24 hours, this month ,etc).

**Comment by YannickRe** [comment]
That’s a separate issue (that indeed existed before). What I’m reporting now is the fact that the refiners don’t return to the initial state when changing the input on the search box.
In the integrated version, if you switched queries, the refiners would be reset as well.

**Comment by FranckyC** [comment]
@YannickRe yup you're right. Didn't see this, I was focusing on the date issue. I removed the search query proeprty connection from the search results, that's why I guess. Not so much time this weekend but I'll try to fix this asap.

**Comment by YannickRe** [comment]
No problem, and no hurry. I’d love to expose the complete SearchService configuration of the current query for use in another webpart, which can be used to determine difference with previous query but allows for complete replay of the Search request for other purposes. What do you think?
